apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.fullname" . }}-config
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
data:
  config.json: |-
    {{- .Files.Get "files/config.json" | nindent 4 }}