---
- name: Include wipe tasks if enabled
  include_tasks: 0-wipe.yml
  when: web_app_full_wipe | default(false)
  tags:
    - wipe

- name: Setup Application Environment
  block:
    - name: Create application directory
      file:
        path: "{{ app_directory }}"
        state: directory
        mode: '0755'

    - name: Template docker-compose file
      template:
        src: docker-compose.yml.j2
        dest: "{{ app_directory }}/docker-compose.yml"
      tags:
        - config
  tags:
    - setup

- name: Manage Application
  block:
    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull
        force_source: yes
      tags:
        - deploy

    - name: Start application with docker-compose
      docker_compose:
        project_src: "{{ app_directory }}"
        state: present
      tags:
        - deploy
  tags:
    - app

- name: Create and start container
  docker_container:
    name: "{{ app_container_name }}"
    image: "{{ app_image }}"
    state: started
    restart_policy: unless-stopped
    ports:
      - "{{ app_external_port }}:{{ app_port }}"
    env:
      TZ: "Europe/Moscow" 