apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-install"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-post-install"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: busybox
        command: ["sh", "-c", "echo Post-install hook running && sleep 60"]