server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ["monitoring-python_app-1"]
    
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'

    pipeline_stages:
      - regex:
          expression: '(?P<ip>[\d\.]+) - - \[(?P<timestamp>.*?)\] "(?P<method>[A-Z]+) (?P<path>[^ ]+) (?P<protocol>[^"]+)" (?P<status>\d+)'
      - labels:
          ip:
          method:
          path:
          status:

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*log

  - job_name: python_app
    static_configs:
      - targets:
          - localhost
        labels:
          job: python_app
          __path__: /var/log/python_app.log

    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag
            time: time 